name: Deploy Build to Github Pages

on:
  push:
    branches:
      - master  # Adjust this to your main branch name

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'

      - name: Install gh-pages
        run: npm install gh-pages
      
      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          npx --no-install gh-pages -d ./dist