name: Release and Deploy

on:
  push:
    branches:
      - master  # Adjust this to your main branch name

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Install dependencies
        run: npm install

      - name: Lint Commit Messages
        run: |
          if git rev-parse HEAD~1 >/dev/null 2>&1; then
            npx commitlint --from=HEAD~1 --to=HEAD
          else
            echo "Skipping commitlint as there is only one commit."
          fi
      - name: Run Build Process
        run: npm run build

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
      
      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          npx --no-install gh-pages -d ../../dist